/** English → Arabic (MSA menu) for tag translations */
export const EN_TO_AR = {
  "Acuka (Spicy Spread)": "أجوка",
  "Aged Kashar Cheese": "جبنة كاشار معتقة",
  "Apricot Jam": "مربى مشمش",
  Arugula: "جرجير",
  "BIG Sauce": "صلصة BIG",
  Banana: "موز",
  "Barley Risotto": "ريzotto بالشعير",
  Basil: "ريحان",
  "Bazlama Bread": "خبز bazlama",
  "Başbaş Bulgur Pilaf": "برغل باشباش",
  "Başbaş Rice": "أرز باشباش",
  "Beef Meatballs": "كفتة بقر",
  "Beef Short Rib": "ضلع بقر",
  "Beef Sucuk": "سجق بقر",
  "Beef Tenderloin": "فيليه بقر",
  "Beef Tenderloin & Boneless Thigh": "فيليه بقر وفخذ دجاج بدون عظم",
  "Berray's Sauce": "صلصة Berray's",
  "Black Olives": "زيتون أسود",
  "Black Rice": "أرز أسود",
  "Blackberry Sauce": "صلصة توت أسود",
  "Boiled Egg": "بيض مسلوق",
  "Bolognese Sauce": "صلصة بولونيز",
  "Boneless Chicken": "دجاج بدون عظم",
  "Boneless Thigh": "فخذ بدون عظم",
  "Braided Cheese": "جبنة مجدولة",
  Broccoli: "بروكلي",
  "Burger Patty": "قرص برجر",
  "Burger Sauce": "صلصة برجر",
  Butter: "زبدة",
  "Caesar Dressing": "صلصة سيزar",
  "Café de Paris Sauce": "صلصة Café de Paris",
  "Cajun Spice": "بهارات cajun",
  Capers: "كبر",
  "Caramelized Onion": "بصل مكرمل",
  Carrot: "جزر",
  Cauliflower: "قرنبيط",
  "Cheddar Cheese": "جبنة cheddar",
  "Cheddar Slice": "شريحة cheddar",
  "Cheese Platter": "طبق جبن",
  Cherries: "كرز",
  "Cherry Tomatoes": "طماطم كرزية",
  Chicken: "دجاج",
  "Chicken Breast": "صدر دجاج",
  "Chicken Tenderloin": "فيليه دجاج",
  Chickpeas: "حمص",
  "Chili Oil": "زيت حار",
  "Chili Pepper": "فلفل حار",
  "Chocolate Chip": "رقائق شوكولاta",
  "Cigar Rolls": "بوريك سيجار",
  "Clotted Cream": "قشطة",
  Cocoa: "كاكao",
  Coleslaw: "سلطة كولslaw",
  "Crispy Chickpeas": "حمص مقرمش",
  Croissant: "كرواسan",
  Croutons: "خبز محمص",
  Cucumber: "خيار",
  "Cucumber & Tomato": "خيار وطماطم",
  "Cultivated Mushrooms": "فطر",
  "Curly Lettuce": "خس مجعد",
  "Demi-Glace Sauce": "صلصة demi-glace",
  Dill: "شبت",
  "Dried Apricots": "مشمش مجفف",
  "Dried Figs": "تين مجفف",
  "Dried Thyme": "زعتر مجفف",
  "Eggplant Purée": "بورée باذنجان",
  Espresso: "إسبريسو",
  "Ezine Cheese": "جبنة إزين",
  Falafel: "فلافل",
  Flour: "دقيق",
  "French Fries": "بطاطس مقلية",
  "Fresh Greens": "خضار ورقية",
  "Fresh Herb Butter": "زبدة بالأعشاب",
  "Fresh Kashar Cheese": "جبنة كاشار طازجة",
  "Fresh Mozzarella": "mozzarella طازجة",
  "Fresh Vegetable Platter": "طبق خضار طازجة",
  "Fruit Platter": "طبق فواكه",
  Fusilli: "fusilli",
  Garlic: "ثوم",
  "Gherkin Pickles": "مخلل خيار",
  "Green Apple": "تفاح أخضر",
  "Green Herb Oil": "زيت أعشاب",
  "Green Lentils": "عدس أخضر",
  "Green Olives": "زيتون أخضر",
  "Half Avocado": "نصف أفوكado",
  Honey: "عسل",
  "Hot Pepper": "فلفل حار",
  Hummus: "حمص",
  "Iceberg Lettuce": "خس iceberg",
  "Kashar Cheese": "جبنة كاشار",
  "Kaygana (Herb Omelette)": "kaygana",
  "Lamb Chops": "ريش غنم",
  Lemon: "ليمون",
  "Lemon Flavored": "بنكهة ليمون",
  Lettuce: "خس",
  "Lorolosso Cheese": "جبنة lorolosso",
  "Meaty Beef Short Rib": "ضلع بقر باللحم",
  Milk: "حليب",
  Mint: "نعناع",
  "Mint Lemon": "نعناع وليمون",
  Mozzarella: "mozzarella",
  "Mozzarella Cheese": "جبنة mozzarella",
  Nutella: "Nutella",
  "Oil & Lemon Vinaigrette": "صلصة زيت وليمون",
  "Olive Oil": "زيت زيتون",
  "Olive Paste": "معجون زيتون",
  Orange: "برتقال",
  "Orange Sauce": "صلصة برtقال",
  "Orange Vinaigrette": "صلصة برtقال",
  "Pan-Fried Eggs": "بيض مقلي",
  Pancakes: "بانكيك",
  Pappardelle: "pappardelle",
  Parmesan: "parmesan",
  "Parmesan Cheese": "جبنة parmesán",
  Parsley: "بقدونس",
  "Pickled Red Cabbage": "مخلل ملفوف أحمر",
  Pickles: "مخلل",
  "Pink Tomato Mince": "لحم مفروم بالطماطم الوردية",
  "Pink Tomatoes": "طماطم وردية",
  "Pita Chips": "رقائق خبز",
  "Pizza Tomato Sauce": "صلصة طماطم للبيتza",
  "Pişi (Fried Dough)": "بيشي",
  Plain: "سادة",
  "Potato Salad": "سلطة بطاطس",
  Potatoes: "بطاطس",
  Purslane: "بقلة",
  Quinoa: "كينoa",
  Raisins: "زبيب",
  "Red Pepper Flakes": "فلفل أحمر مطحون",
  "Red Pepper Oil": "زيت فلفل أحمر",
  Rigatoni: "rigatoni",
  "Roasted Eggplant": "باذنجان مشوي",
  "Roasted Green Pepper": "فلفل أخضر مشوي",
  "Roasted Kapya Pepper": "فلفل كابيا مشوي",
  "Roasted Onion": "بصل مشوي",
  "Roasted Pepper": "فلفل مشوي",
  "Roasted Red Pepper": "فلفل أحمر مشوي",
  "Roasted Tomato": "طماطم مشوية",
  Salt: "ملح",
  "Seasoned Flour Mix": "خليط دقيق متبل",
  "Seasoned French Fries": "بطاطس مقلية متبلة",
  "Seasoned Potatoes": "بطاطس متبلة",
  "Shredded Meat": "لحم مفتت",
  "Shredded Mozzarella": "mozzarella مبشورة",
  "Smoked Beef Short Rib": "ضلع بقر مدخن",
  "Smoked Meat": "لحم مدخن",
  Spaghetti: "سباغيتي",
  "Special Spiced Sauce": "صلصة خاصة متبلة",
  "Spiced Sauce": "صلصة متبلة",
  "Spicy Aioli": "آيولي حار",
  "Spicy Aioli Sauce": "صلصة آيولي حارة",
  "Spicy Butter": "زبدة حارة",
  "Spicy Chili Pepper": "فلفل حار",
  "Spinach Béchamel": "بشamel بالسبانخ",
  "Spinach Béchamel Sauce": "صلصة بشamel بالسبانخ",
  "Strained Yogurt": "لبن مصفى",
  "Strained Yogurt with Browned Butter": "لبن مصفى بزبدة محمرة",
  Strawberry: "فراولة",
  "Strawberry Jam": "مربى فراولة",
  "Strawberry Sauce": "صلصة فراولة",
  "Strawberry Vinaigrette": "صلصة فراولة",
  "Sucuk & Halloumi": "سجق وحلوم",
  Sumac: "سماق",
  "Sun-Dried Tomatoes": "طماطم مجففة",
  "Sweet & Sour Sauce": "صلصة حلوة حامضة",
  "Syrup Flavored": "بنكهة شراب",
  "Syrup Flavors": "نكهات شراب",
  Tahini: "طحينة",
  "Tahini & Grape Molasses": "طحينة ودبس",
  Tenderloin: "فيليه",
  Tomato: "طماطم",
  "Tomato Sauce": "صلصة طmاطم",
  "Tortilla Lavash": "خبز tortilla",
  "Truffle Oil": "زيت trufle",
  "Tırnak Bread": "خبز tırnak",
  "Tırnak Flatbread": "خبز tırnak",
  "Vegetable Clove BBQ Sauce": "صلصة بارbecue بالخضار",
  Walnuts: "جوز",
  "Watermelon Lemon": "بطيخ وليمون",
  "Watermelon Sauce": "صلصة بطيخ",
  "Wheat Berries": "قمح",
  "White Cheese": "جبنة بيضاء",
  Zucchini: "كوسا",
  "Zucchini Fritters": "مُجَوَّر كوسا",
};

export const ITEM_EN_TO_AR = {
  "French Fries": "بطاطس مقلية",
  "Zucchini Fritters": "مُجَوَّر كوسا",
  "Cauliflower Broccoli Tabouleh": "تبولة قرنبيط وبروكلي",
  "Crispy Chicken": "دجاج مقرمش",
  Hummus: "حمص",
  "Truffle French Fries": "بطاطس مقلية بالكمأة",
  "Meat Gyoza": "جyoza باللحم",
  "Cheese Platter": "طبق جبن",
  "Cup of Tea": "فنجان شاي",
  Milkshake: "مilkshake",
  Hamburger: "برجر",
  "Lamb Chops": "ريش غنم",
  "Combo Fajita": "فاهita مشكلة",
  "Shredded Meat Burger": "برجر لحم مفتت",
  "Mini Burger": "برجر صغير",
  "Yogurt Kebab": "كباب باللبن",
  "Chicken Fajita": "فاهita دجاج",
  "Chicken Burger": "برجر دجاج",
  "Cheese Burger": "برجر بالجبن",
  "Beef Fajita": "فاهita لحم",
  "Berray's Burger": "برجر Berray's",
  "Chicken Schnitzel": "schnitzel دجاج",
  "Chicken Piccata": "piccata دجاج",
  "Başbaş Tenderloin": "فيليه باشباش",
  "Grilled Chicken": "دجاج مشوي",
  "Akçaabat Meatballs": "köfte أكçaabat",
  "BBQ Chicken Clove": "دجاج بالبارbecue",
  Bistecca: "bistecca",
  "Meaty Short Rib": "ضلع بقر باللحم",
  "Vegan Bowl": "طبق نباتي",
  "Berray's Special": "خاص Berray's",
  "Lentil Soup": "شوربة عدس",
  "Cold Soup": "شوربة باردة",
  "Başbaş Rice": "أرز باشباش",
  "Eggplant Purée": "بورée باذنجان",
  Mushrooms: "فطر",
  Onion: "بصل",
  Potatoes: "بطاطس",
  Pepper: "فلفل",
  Sucuk: "سجق",
  Cheese: "جبنة",
  "Plain Omelette": "عجة سادة",
  "Turkish Breakfast Spread (2 People)": "فطور تركي (شخصان)",
  "Breakfast Plate": "طبق فطور",
  "Eggs with Sucuk": "بيض بالسجق",
  Menemen: "menemen",
  "Eggs with Sautéed Meat": "بيض باللحم المقلي",
  "Plain Sautéed Meat": "لحم مقلي",
  "Pan-Fried Eggs": "بيض مقلي",
  Muhlama: "muhlama",
  "Fresh Vegetable Platter": "طبق خضار طازجة",
  Kaygana: "kaygana",
  "Yogurt Granola": "granola باللبن",
  "Chocolate Fruit Croissant": "كرواسan بالشوكولاta والفواكه",
  "Blue Orange Bubble Tea": "bubble tea برتقال أزرق",
  "Hibiscus Lime": "hibiscus ولime",
  Mojito: "mojito",
  "Strawberry Mojito": "mojito فراولة",
  "Cool Lime": "cool lime",
  "Purple Sky": "purple sky",
  "Watermelon Fizz": "watermelon fizz",
  "Butterfly Bubble Tea": "bubble tea فراشة",
  "Dragonia Bubble Tea": "bubble tea dragonia",
  "Lamb's Ear": "كوكتيل أذن الغنم",
  "Spaghetti Pomodoro": "سباغيتي pomodoro",
  "Meat Pappardelle": "pappardelle باللحم",
  "Vegetable Fusilli": "fusilli بالخضار",
  "Rigatoni Bolognese": "rigatoni bolonez",
  Cola: "كولا",
  "Cola Zero": "كولا zero",
  Fanta: "Fanta",
  Sprite: "Sprite",
  "Iced Tea": "شاي مثلج",
  "Cappy Fruit Juice": "عصير Cappy",
  "Plain Soda": "صودa سادة",
  "Flavored Soda": "صودa بنكهة",
  "Kisarna Mineral Water": "مياه Kisarna معدنية",
  Schweppes: "Schweppes",
  "Glass Bottle Water (330ml)": "ماء زجاجة (330ml)",
  "Glass Bottle Water (750ml)": "ماء زجاجة (750ml)",
  "Margherita Pizza": "بيتza margherita",
  "Smoked Meat Pizza": "بيتza لحم مدخن",
  "Pomodoro Pizza": "بيتza pomodoro",
  "Tenderloin Pizza": "بيتza فيليه",
  "Strawberry Purslane Salad": "سلطة بقلة وفراولة",
  "Quinoa Chopped Salad": "سلطة كينoa مقطعة",
  "Chicken Caesar Salad": "سلطة سيزar بالدجاج",
  "Tomato Arugula Salad": "سلطة طmاطm وجرjir",
  Cortado: "cortado",
  Espresso: "إسبريسو",
  "Double Espresso": "إسبريسو مزdوج",
  Americano: "americano",
  "White Mocha": "white mocha",
  "Toffenut Latte": "toffenut latte",
  "Cookies Latte": "cookies latte",
  "Honey Milk": "حليب بالعسل",
  "Hot Chocolate": "شوكولاta ساخنة",
  "Caramel Latte": "caramel latte",
  Mocha: "mocha",
  Cappuccino: "cappuccino",
  Latte: "latte",
  "Flat White": "flat white",
  "Filter Coffee": "قهوة فلتر",
  "Turkish Coffee with Milk": "قهوة ترkية بالحليب",
  "Turkish Coffee": "قهوة ترkية",
  Tea: "شاي",
  "Coffee with Milk": "قهوة بالحليب",
  "Iced Filter Coffee": "قهوة فلتر مثلجة",
  "Iced Hot Chocolate": "شوكولاta باردة",
  Frappe: "frappé",
  "Blackberry Lemonade": "ليمونada توt",
  "Iced Mocha": "iced mocha",
  "Iced White Mocha": "iced white mocha",
  "Iced Cookies Latte": "iced cookies latte",
  "Iced Toffenut Latte": "iced toffenut latte",
  Affogato: "affogato",
  "Pomegranate Juice": "عصير رمان",
  "Atom Juice": "عصير Atom",
  "Orange Juice": "عصير برtقال",
  Lemonade: "ليمونada",
  "Mixed Frozen": "frozen مشكلة",
  Frozen: "frozen",
  "Iced Americano": "iced americano",
  "Iced Latte": "iced latte",
  "Mint Lemonade": "ليمونada بالنعناع",
  "Mango Lemonade": "ليمونada مانgo",
  "Strawberry Lemonade": "ليمونada فراولة",
  "Ice Cream": "آيس cream",
  "Levain Cookie": "levain cookie",
  "White Chocolate Tahini Soufflé": "soufflé شوكولاta بيضاء وطحينة",
  "Sour Cherry Brownie": "brownie كرز حامض",
  "Strawberry Magnolia": "magnolia فراولة",
  Tiramisu: "tiramisu",
  "Strawberry Cheesecake": "cheesecake فراولة",
  "Merguez Roll": "rulat merguez",
  "Chocolate Straji": "chocolate straji",
  "Fruit Platter": "طبق فواكه",
  "Forest Berry Craquelin": "craquelin توt",
  "Bazlama Toast": "tost bazlama",
  "Mixed Bazlama Toast": "tost bazlama مشكل",
};

export const CATEGORY_EN_TO_AR = {
  Starters: { nameAr: "المقبلات", descriptionAr: "مقبلات للمشاركة، لقيمات مقرمشة، ونكهات تفتح الشهية." },
  "Main Courses": { nameAr: "الأطباق الرئيسية", descriptionAr: "أطباق رئيسية مشبعة من المشاوي والفajita والكلاسيكيات." },
  Burgers: { nameAr: "البرجر", descriptionAr: "برجر منزلي — من الكلاسيكي إلى توقيع Berray's." },
  Soups: { nameAr: "الشوربات", descriptionAr: "خيارات شوربة دافئة ومنعشة." },
  Extras: { nameAr: "الإضافات", descriptionAr: "أطباق جانبية يمكنك إضافتها إلى طلبك." },
  Breakfast: { nameAr: "الفطور", descriptionAr: "من العجة إلى فطور تركي — بداية لطيفة لليوم." },
  Cocktails: { nameAr: "المشروبات المختلطة", descriptionAr: "bubble tea وmojito وخلطات توقيعية." },
  Pasta: { nameAr: "المعكرونة", descriptionAr: "أطباق معكرونة طازجة من pomodoro إلى bolonez." },
  "Soft Drinks": { nameAr: "المشروبات الغازية", descriptionAr: "مشروبات غازية وصودa ومشروبات باردة." },
  Pizza: { nameAr: "البيتza", descriptionAr: "بيتza رقيقة طازجة من الفrn." },
  Salads: { nameAr: "السلطات", descriptionAr: "خضار طازجة وأطباق سلطة مشبعة." },
  "Hot Drinks": { nameAr: "المشروبات الساخنة", descriptionAr: "قهوة إسبريسو ومشروبات ساخنة." },
  "Cold Drinks": { nameAr: "المشروبات الباردة", descriptionAr: "قهوة مثلجة وعصير ليمون وعصائر طازجة." },
  Desserts: { nameAr: "الحلويات", descriptionAr: "من soufflé إلى cheesecake — خاتمة حلوة." },
  Toasts: { nameAr: "الtoast", descriptionAr: "toast سادة ومشكلة على خبز bazlama." },
};

export function enToAr(en, map) {
  if (map[en]) return map[en];
  throw new Error(`Missing Arabic for: ${en}`);
}
